# This file is to easy configure development enviroment
# Last automatic file update/creation was on 2016-05-05 10:16:17 +0300
# More info could be found at http://impresscms.org

# ---------------------------------------------------------------------------------------
# IP of this virtual machine.
# ---------------------------------------------------------------------------------------
ip: 192.168.201.65

# ---------------------------------------------------------------------------------------
# You can type this hostname in your browser and launch the website
# ---------------------------------------------------------------------------------------
hostname: 
    -   seabattle.dev

# ---------------------------------------------------------------------------------------
# This is name how is box is listed in virtual machine 
# ---------------------------------------------------------------------------------------
name: seabattle-dev

# ---------------------------------------------------------------------------------------
# SSH Keys. If you use GitHub client, you can just simply change "id_rsa" to "github_rsa"
# and everything should work without any extended configuration.
#
# If you remove lines these lines below, code in vagrantfile will try to autodetect
# where your keys are located. If it fails, it raise an error.
# ---------------------------------------------------------------------------------------
#keys:
#     private: ~/.ssh/id_rsa
#     public: ~/.ssh/id_rsa.pub

# ---------------------------------------------------------------------------------------
# Defines ports forwarted list
# ---------------------------------------------------------------------------------------
ports:
     - host: 6667
       guest: 6667

# ---------------------------------------------------------------------------------------
# How many CPUs should this box use? Default value is 1.
# ---------------------------------------------------------------------------------------
cpus: 1

# ---------------------------------------------------------------------------------------
# How much RAM should this box have? This is a number in megabytes. Default value is 512.
# ---------------------------------------------------------------------------------------
memory: 512

# ---------------------------------------------------------------------------------------
# Do we need to check automatically for box updates? Default value is false
# ---------------------------------------------------------------------------------------
check_update: false

# ---------------------------------------------------------------------------------------
# What shell commands will be executed on provision?
# ---------------------------------------------------------------------------------------
provision: |
  cat >/tmp/ngircd.conf <<'EOF'

  [Global]
  Name = seabattle.dev
  Info = Example server for seabattle
  Listen = 0.0.0.0
  MotdPhrase = "Come to #seabattle channel!"
  Ports = 6667, 6668, 6669, 7000
  ServerGID = ngircd
  ServerUID = ngircd

  [Channel]
  Name = #seabattle
  Topic = Channel where seabattle bot sits
  EOF

  cat > /tmp/eggdrop.conf <<'EOF'
  # Gemaakt door de generator stafke.be and thx to Zeroke
  # http://www.stafke.be

  set botnet-nick "seabattle"
  set mod-path "/usr/lib/eggdrop/modules/"
  set help-path "/usr/share/eggdrop/help/"
  set my-hostname "127.0.0.1"
  set protect-telnet 0
  set dcc-sanitycheck 0
  set ident-timeout 5
  set require-p 0
  set open-telnets 0
  set stealth-telnets 0
  set use-telnet-banner 0
  set connect-timeout 90
  set dcc-flood-thr 3
  set telnet-flood 5:60
  set paranoid-telnet-flood 1
  set resolve-timeout 15
  set max-dcc 50
  set dcc-portrange 1024:65535
  set enable-simul 1
  set allow-dk-cmds 1

  loadmodule dns
  loadmodule channels
  loadmodule server
  loadmodule ctcp
  loadmodule irc
  loadmodule notes
  loadmodule console
  loadmodule transfer
  loadmodule share
  checkmodule blowfish

  set nick "Seabattle"
  set altnick "Vagrant"
  set admin "owner"
  set realname "Bot for Games.lt"
  set shortnick "Seabattle bot"
  set servers {
    127.0.0.1:6667
  }

  channel add #vagrant {
    chanmode "+nt"
    idle-kick 0
    stopnethack-mode 0
  }

  channel add #seabattle {
    chanmode "+nt"
    idle-kick 0
    stopnethack-mode 0
  }

  channel set #vagrant +enforcebans +dynamicbans +userbans
  channel set #vagrant +dynamicexempts +userexempts +dynamicinvites +userinvites
  channel set #vagrant -autoop -bitch +protectops +protectfriends +dontkickops
  channel set #vagrant +greet +statuslog
  channel set #vagrant +revenge +autovoice
  channel set #vagrant -secret +shared +cycle
  channel set #vagrant -inactive -seen +nodesynch

  channel set #seabattle +enforcebans +dynamicbans +userbans
  channel set #seabattle +dynamicexempts +userexempts +dynamicinvites +userinvites
  channel set #seabattle -autoop -bitch +protectops +protectfriends +dontkickops
  channel set #seabattle +greet +statuslog
  channel set #seabattle +revenge +autovoice
  channel set #seabattle -secret +shared +cycle
  channel set #seabattle -inactive -seen +nodesynch

  set net-type 5

  listen 3333 all

  set owners ""

  set userfile "/home/vagrant/seabattle.user"
  set chanfile "/home/vagrant/seabattle.chan"
  set temp-path ""
  logfile msbxco * "/vagrant/logs/seabattle.log"
  logfile jpk #vagrant "/vagrant/logs/seabattle.log"

  set init-server { putserv "MODE Seabattle +B-ws" }

  source /usr/share/eggdrop/scripts/alltools.tcl
  source /usr/share/eggdrop/scripts/action.fix.tcl
  source /usr/share/eggdrop/scripts/compat.tcl
  source /usr/share/eggdrop/scripts/userinfo.tcl
  source /vagrant/src/seabattle.tcl

  loadhelp userinfo.help
  EOF

  sudo bash <<'EOF'
    DEBIAN_FRONTEND=noninteractive apt-get -y install npm tcl mysqltcl mysql-server unzip mc irssi ngircd eggdrop apache2 screen composer git php-cli php-curl php-json php-mbstring php-mcrypt php-gettext php-zip php libapache2-mod-php

    service mysql restart

    mysql -e "CREATE DATABASE seabattle;"
    mysql seabattle < /vagrant/src/seabattle.sql

    mv /tmp/ngircd.conf /etc/ngircd.conf
    service ngircd restart

    mv /tmp/eggdrop.conf /etc/eggdrop.conf
    chmod 0777 /var/www/html
    rm -rf /var/www/html/index.html
    touch /var/www/html/index.php
    chmod 0777 /var/www/html/index.php
  EOF

  cd /var/www/html

  cat > /tmp/config.js <<'EOF'
  var conf = {
      // user: '',
      // group: '',
      log: "kiwi.log",
      servers: [],
      outgoing_address: {
        IPv4: '0.0.0.0'
        //IPv6: '::'
      },
      identd: {
        enabled: false,
        port: 113,
        address: "0.0.0.0"
      },
      public_http: "client/",
      /* client_transports: [
        'polling'
      ], */
      max_client_conns: 5,
      max_server_conns: 0,
      default_encoding: 'utf8',
      default_gecos: '%n is using a Web IRC client',
      default_ident: '%i',
      quit_message: '',
      ircd_reconnect: true,
      client_plugins: [],
      module_dir: "../server_modules/",
      modules: [],
      webirc_pass: '',
      reject_unauthorised_certificates: false,
      http_proxies: ["127.0.0.1/32"],
      http_proxy_ip_header: "x-forwarded-for",
      http_base_path: "/kiwi",
      socks_proxy: {
        enabled: false,
        all: false,
        proxy_hosts: [

        ],
        address: '127.0.0.1',
        port: 1080,
        user: null,
        pass: null
      },
      client: {
          server: '127.0.0.1',
          port:    6667,
          ssl:     false,
          channel: '#seabattle',
          channel_key: '',
          nick:    'kiwi_?',
          settings: {
              theme: 'relaxed',
              text_theme: 'default',
              channel_list_style: 'tabs',
              scrollback: 250,
              show_joins_parts: true,
              show_timestamps: false,
              use_24_hour_timestamps: true,
              mute_sounds: false,
              show_emoticons: true,
              ignore_new_queries: false,
              count_all_activity: false,
              show_autocomplete_slideout: true,
              locale: null // null = use the browser locale settings
          },
          window_title: 'Kiwi IRC'
      },
      client_themes: [
         'relaxed',
         'mini',
         'cli',
         'basic'
      ]
    };

    conf.servers.push({
        port:   7778,
        address: "0.0.0.0"
    });

    /*
     * Do not amend the below lines unless you understand the changes!
     */
    module.exports.production = conf;
  EOF

  git clone --depth=1 https://github.com/prawnsalad/KiwiIRC.git
  pushd KiwiIRC
    DEBIAN_FRONTEND=noninteractive npm install
    mv /tmp/config.js ./config.js
    ./kiwi build
    ./kiwi start
  popd

  git clone --depth=1 https://github.com/phpmyadmin/phpmyadmin.git phpmyadmin
  pushd phpmyadmin
  composer update
  popd

  composer require symfony/yaml
  composer require beelab/bowerphp
  ./vendor/bin/bowerphp install bootstrap
  ./vendor/bin/bowerphp install font-awesome

  cd /var/www/html

  cat > style.css <<'EOF'
  h1 {
      display: block;
      width: 100%;
      text-align: center;
  }
  a {
      color: #337ab7;
      text-decoration: none;
      display: block;
  }
  div a {
    display: inline;
    width: 100%;
  }
  li {
    display: inline-block;
  }
  EOF

  cat > index.php <<'EOF'
  <?php
      require __DIR__ . '/vendor/autoload.php';

      $config = \Symfony\Component\Yaml\Yaml::parse(file_get_contents('/vagrant/config.yaml'));
  ?>
  <!DOCTYPE html>
  <html>
  <head>
  <meta charset="UTF-8">
  <title>Seabattle</title>
  <link href="bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
  <link href="bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="style.css" rel="stylesheet">
  </head>
  <body>
    <div class="jumbotron">
      <ul>
        <li>
        <h1 class="fa fa-comments" aria-hidden="true"></h1>
        <?php if (!empty($config['ip'])): ?>
          <a href="irc://<?=$config['ip']; ?>#seabattle"><?=$config['ip']; ?></a>
        <?php else: ?>
          <a href="irc://<?=getHostByName(getHostName()); ?>#seabattle"><?=getHostByName(getHostName()); ?></a>
        <?php endif; ?>
        <div>(<?php if (!empty($config['ip'])): ?><a href="http://<?=$config['ip']; ?>:7778">KiwiIRC</a><?php else: ?><a href="http://<?=getHostByName(getHostName()); ?>:7778">KiwiIRC</a><?php endif; ?>)</div>
      </li>
      <li>
        <h1 class="fa fa-file-text-o" aria-hidden="true"></h1>
        <a href="/phpmyadmin/">/phpmyadmin/</a>
      </li>
    </div>
  </body>
  </html>
  EOF

  (crontab -l; echo "@reboot screen -dm -S eggdrop eggdrop -m /etc/eggdrop.conf" ) | crontab -
  (crontab -l; echo "@reboot /var/www/html/KiwiIRC/kiwi start" ) | crontab -
  screen -dm -S eggdrop eggdrop -m /etc/eggdrop.conf
  /var/www/html/KiwiIRC/kiwi start

  sudo chown -R www-data /var/www/html/
