FROM ubuntu:latest

EXPOSE 6667/tcp

ARG SEABATTLE_QSTAT_FLAG=.
ARG SEABATTLE_BOT_PASS=botsky
ARG SEABATTLE_SKYSTATS_MAX=10
ARG SEABATTLE_SKYSTATS_I=0
ARG SEABATTLE_DB_USER=seabattle
ARG SEABATTLE_DB_PASS=seabattle
ARG SEABATTLE_DB_NAME=seabattle
ARG SEABATTLE_LANGUAGE=en
ARG SEABATTLE_GRID_HORIZONTAL_WORD=games
ARG SEABATTLE_GRID_VERTICAL_WORD=12345
ARG SEABATTLE_SHIPS_COUNT=5
ARG SEABATTLE_NICKSERV_AUTH_NEEDED=false
ARG SEABATTLE_NICKSERV_HOST=aitvarasnet.org
ARG SEABATTLE_NICKSERV_TIMEOUT=5
ARG SEABATTLE_LOG_QUERIES=no

ENV SEABATTLE_QSTAT_FLAG=$SEABATTLE_QSTAT_FLAG
ENV SEABATTLE_BOT_PASS=$SEABATTLE_BOT_PASS
ENV SEABATTLE_SKYSTATS_MAX=$SEABATTLE_SKYSTATS_MAX
ENV SEABATTLE_SKYSTATS_I=$SEABATTLE_SKYSTATS_I
ENV SEABATTLE_DB_USER=$SEABATTLE_DB_USER
ENV SEABATTLE_DB_PASS=$SEABATTLE_DB_PASS
ENV SEABATTLE_DB_HOST=127.0.0.1
ENV SEABATTLE_DB_NAME=$SEABATTLE_DB_NAME
ENV SEABATTLE_LANGUAGE=$SEABATTLE_LANGUAGE
ENV SEABATTLE_GRID_HORIZONTAL_WORD=$SEABATTLE_GRID_HORIZONTAL_WORD
ENV SEABATTLE_GRID_VERTICAL_WORD=$SEABATTLE_GRID_VERTICAL_WORD
ENV SEABATTLE_SHIPS_COUNT=$SEABATTLE_SHIPS_COUNT
ENV SEABATTLE_NICKSERV_AUTH_NEEDED=$SEABATTLE_NICKSERV_AUTH_NEEDED
ENV SEABATTLE_NICKSERV_HOST=$SEABATTLE_NICKSERV_HOST
ENV SEABATTLE_NICKSERV_TIMEOUT=$SEABATTLE_NICKSERV_TIMEOUT
ENV SEABATTLE_LOG_QUERIES=$SEABATTLE_LOG_QUERIES

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y tcl mysqltcl mysql-server eggdrop mysql-client && \
    apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get autoremove -y

COPY install.sql /seabattle_install.sql
RUN mysql -e "CREATE DATABASE $SEABATTLE_DB_NAME;" && \
    mysql -e "CREATE USER '$SEABATTLE_DB_USER'@'%' IDENTIFIED BY '$SEABATTLE_DB_PASS';" && \
    mysql -e "GRANT ALL PRIVILEGES ON * . * TO '$SEABATTLE_DB_NAME'@'%';" && \
    mysql -e "FLUSH PRIVILEGES;"
    mysql $SEABATTLE_DB_NAME < /seabattle_install.sql
