FROM phusion/baseimage:latest

EXPOSE 6667/tcp

ARG SEABATTLE_QSTAT_FLAG=.
ARG SEABATTLE_BOT_PASS=botsky
ARG SEABATTLE_SKYSTATS_MAX=10
ARG SEABATTLE_SKYSTATS_I=0
ARG SEABATTLE_LANGUAGE=en
ARG SEABATTLE_GRID_HORIZONTAL_WORD=games
ARG SEABATTLE_GRID_VERTICAL_WORD=12345
ARG SEABATTLE_SHIPS_COUNT=5
ARG SEABATTLE_NICKSERV_AUTH_NEEDED=false
ARG SEABATTLE_NICKSERV_HOST=aitvarasnet.org
ARG SEABATTLE_NICKSERV_TIMEOUT=5
ARG SEABATTLE_LOG_QUERIES=no
ARG EGGDROP_BOTNET_NICK=seabattle
ARG EGGDROP_PROTECT_TELNET=0
ARG EGGDROP_DCC_SANITY_CHECK=0
ARG EGGDROP_IDENT_TIMEOUT=5
ARG EGGDROP_REQUIRE_PARTY=0
ARG EGGDROP_OPEN_TELNETS=0
ARG EGGDROP_STEALTH_TELNETS=0
ARG EGGDROP_USE_TELNET_BANNER=0
ARG EGGDROP_CONNECTION_TIMEOUT=90
ARG EGGDROP_DCC_FLOOD_THR=3
ARG EGGDROP_TELNET_FLOOD=5:60
ARG EGGDROP_PARANOID_TELNET_FLOOD=1
ARG EGGDROP_RESOLVE_TIMEOUT=15
ARG EGGDROP_MAX_DCC=50
ARG EGGDROP_DCC_PORTRANGE=1024:65535
ARG EGGDROP_ENABLE_SIMUL=1
ARG EGGDROP_ALLOW_DK_CMDS=1
ARG EGGDROP_MODULES="dns channels server ctcp irc notes console transfer share"
ARG EGGDROP_CHECK_MODULES=blowfish
ARG EGGDROP_NICK=Seabattle
ARG EGGDROP_ALTNICK=SeabattleBot
ARG EGGDROP_ADMIN=owner
ARG EGGDROP_REAL="Bot for Games.lt"
ARG EGGDROP_SHORTNICK="SeaBattle bot"
ARG EGGDROP_SERVERS=aitvarasnet.org
ARG EGGDROP_CHANNELS="#seabattle"
ARG EGGDROP_NET_TYPE=5
ARG EGGDROP_LISTEN_USERS_PORT=3333
ARG EGGDROP_LISTEN_BOTS_PORT=3333
ARG EGGDROP_OWNERS=""
ARG EGGDROP_SYSTEM_SCRIPTS="alltools action.fix compat userinfo"
ARG EGGDROP_SYSTEM_HELPS=userinfo

ENV SEABATTLE_QSTAT_FLAG ${SEABATTLE_QSTAT_FLAG}
ENV SEABATTLE_BOT_PASS ${SEABATTLE_BOT_PASS}
ENV SEABATTLE_SKYSTATS_MAX ${SEABATTLE_SKYSTATS_MAX}
ENV SEABATTLE_SKYSTATS_I ${SEABATTLE_SKYSTATS_I}
ENV SEABATTLE_DB_USER root
ENV SEABATTLE_DB_PASS ""
ENV SEABATTLE_DB_HOST 127.0.0.1
ENV SEABATTLE_DB_NAME seabattle
ENV SEABATTLE_LANGUAGE ${SEABATTLE_LANGUAGE}
ENV SEABATTLE_GRID_HORIZONTAL_WORD ${SEABATTLE_GRID_HORIZONTAL_WORD}
ENV SEABATTLE_GRID_VERTICAL_WORD ${SEABATTLE_GRID_VERTICAL_WORD}
ENV SEABATTLE_SHIPS_COUNT ${SEABATTLE_SHIPS_COUNT}
ENV SEABATTLE_NICKSERV_AUTH_NEEDED ${SEABATTLE_NICKSERV_AUTH_NEEDED}
ENV SEABATTLE_NICKSERV_HOST ${SEABATTLE_NICKSERV_HOST}
ENV SEABATTLE_NICKSERV_TIMEOUT ${SEABATTLE_NICKSERV_TIMEOUT}
ENV SEABATTLE_LOG_QUERIES ${SEABATTLE_LOG_QUERIES}
ENV EGGDROP_BOTNET_NICK ${EGGDROP_BOTNET_NICK}
ENV EGGDROP_PROTECT_TELNET ${EGGDROP_PROTECT_TELNET}
ENV EGGDROP_DCC_SANITY_CHECK ${EGGDROP_DCC_SANITY_CHECK}
ENV EGGDROP_IDENT_TIMEOUT ${EGGDROP_IDENT_TIMEOUT}
ENV EGGDROP_REQUIRE_PARTY ${EGGDROP_REQUIRE_PARTY}
ENV EGGDROP_OPEN_TELNETS ${EGGDROP_OPEN_TELNETS}
ENV EGGDROP_STEALTH_TELNETS ${EGGDROP_STEALTH_TELNETS}
ENV EGGDROP_USE_TELNET_BANNER ${EGGDROP_USE_TELNET_BANNER}
ENV EGGDROP_CONNECTION_TIMEOUT ${EGGDROP_CONNECTION_TIMEOUT}
ENV EGGDROP_DCC_FLOOD_THR ${EGGDROP_DCC_FLOOD_THR}
ENV EGGDROP_TELNET_FLOOD ${EGGDROP_TELNET_FLOOD}
ENV EGGDROP_PARANOID_TELNET_FLOOD ${EGGDROP_PARANOID_TELNET_FLOOD}
ENV EGGDROP_RESOLVE_TIMEOUT ${EGGDROP_RESOLVE_TIMEOUT}
ENV EGGDROP_MAX_DCC ${EGGDROP_MAX_DCC}
ENV EGGDROP_DCC_PORTRANGE ${EGGDROP_DCC_PORTRANGE}
ENV EGGDROP_ENABLE_SIMUL ${EGGDROP_ENABLE_SIMUL}
ENV EGGDROP_ALLOW_DK_CMDS ${EGGDROP_ALLOW_DK_CMDS}
ENV EGGDROP_MODULES ${EGGDROP_MODULES}
ENV EGGDROP_CHECK_MODULES ${EGGDROP_CHECK_MODULES}
ENV EGGDROP_NICK ${EGGDROP_NICK}
ENV EGGDROP_ALTNICK ${EGGDROP_ALTNICK}
ENV EGGDROP_ADMIN ${EGGDROP_ADMIN}
ENV EGGDROP_REAL ${EGGDROP_REAL}
ENV EGGDROP_SHORTNICK ${EGGDROP_SHORTNICK}
ENV EGGDROP_SERVERS ${EGGDROP_SERVERS}
ENV EGGDROP_CHANNELS ${EGGDROP_CHANNELS}
ENV EGGDROP_NET_TYPE ${EGGDROP_NET_TYPE}
ENV EGGDROP_LISTEN_USERS_PORT ${EGGDROP_LISTEN_USERS_PORT}
ENV EGGDROP_LISTEN_BOTS_PORT ${EGGDROP_LISTEN_BOTS_PORT}
ENV EGGDROP_OWNERS ${EGGDROP_OWNERS}
ENV EGGDROP_SYSTEM_SCRIPTS ${EGGDROP_SYSTEM_SCRIPTS}
ENV EGGDROP_SYSTEM_HELPS ${EGGDROP_SYSTEM_HELPS}

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y tcl telnet sudo mysqltcl mysql-server eggdrop mysql-client && \
    apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get autoremove -y

COPY ./docker-data/configs/eggdrop.conf /etc/eggdrop.conf

COPY ./docker-data/scripts/entrypoint.sh /usr/bin/run.sh
RUN chmod +x /usr/bin/run.sh

COPY ./install.sql /tmp/seabattle_install.sql
COPY ./docker-data/scripts/configure-db.sh /tmp/configure-db.sh
RUN /usr/bin/env bash /tmp/configure-db.sh

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN useradd -r -U -M -s /bin/false eggdrop
COPY ./src/ /srv/seabattle/
RUN chown -R eggdrop:eggdrop /srv/seabattle/

CMD ["bash"]
#CMD ["telnet" "localhost" ${EGGDROP_LISTEN_PORT}]

ENTRYPOINT ["/usr/bin/run.sh"]
