version: '3'

services:

  seabattle_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: bot.seabattle.internal
    #image: gameslt/seabattle.tcl
    environment:
      SEABATTLE_QSTAT_FLAG: .
      SEABATTLE_BOT_PASS: botsky
      SEABATTLE_SKYSTATS_MAX: 10
      SEABATTLE_SKYSTATS_I: 0
      SEABATTLE_DB_USER: seabattle
      SEABATTLE_DB_PASS: seabattle
      SEABATTLE_DB_HOST: 172.16.0.102
      SEABATTLE_DB_NAME: seabattle
      SEABATTLE_LANGUAGE: en
      SEABATTLE_GRID_HORIZONTAL_WORD: games
      SEABATTLE_GRID_VERTICAL_WORD: 12345
      SEABATTLE_SHIPS_COUNT: 5
      SEABATTLE_NICKSERV_AUTH_NEEDED: "false"
      SEABATTLE_NICKSERV_HOST: irc.seabattle.internal
      SEABATTLE_NICKSERV_TIMEOUT: 5
      SEABATTLE_LOG_QUERIES: "no"
      EGGDROP_NICK: Seabattle
      EGGDROP_ALTNICK: SeabattleBot
      EGGDROP_ADMIN: owner
      EGGDROP_REAL: Bot for Games.lt
      EGGDROP_SHORTNICK: SeaBattle bot
      EGGDROP_SERVERS: 172.16.0.103:6667
      EGGDROP_CHANNELS: "#seabattle"
      EGGDROP_BOTNET_NICK: seabattle
    depends_on:
      - mysql
      - ngircd

  ngircd:
    restart: unless-stopped
    image: geekduck/ngircd
    domainname: irc.seabattle.internal
    ports:
      - 6667:6667
    networks:
      virtual_net:
        ipv4_address: 172.16.0.103

  kiwiirc:
    restart: unless-stopped
    image: boxbox/kiwiirc
    domainname: seabattle.internal
    environment:
      KIWI_SERVER_IP: 192.168.201.65
      KIWI_SERVER_PORT: 6667
      KIWI_JOIN_CHANNEL: '#seabattle'
      KIWI_NICK: 'web_?'
      KIWI_TITLE: Kiwi IRC
      KIWI_PORT: 7778
      KIWI_BIND: 0.0.0.0
    volumes:
      - ./docker-data/configs/kiwiirc.js:/app/config.js
    ports:
      - 7778:7778
    depends_on:
      - ngircd

  mysql:
    restart: unless-stopped
    image: mysql/mysql-server:5.5
    domainname: db.seabattle.internal
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_DATABASE: seabattle
      MYSQL_USER: seabattle
      MYSQL_PASSWORD: seabattle
    networks:
      virtual_net:
        ipv4_address: 172.16.0.102
    volumes:
      - ./docker-data/logs/mysql:/var/log

networks:
  virtual_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.0.0/24
