version: "3.3"

services:

  seabattle_bot:
    restart: unless-stopped
    image: gameslt/seabattle.tcl
    environment:
      SEABATTLE_QSTAT_FLAG: .
      SEABATTLE_BOT_PASS: botsky
      SEABATTLE_SKYSTATS_MAX: 10
      SEABATTLE_SKYSTATS_I: 0
      SEABATTLE_DB_USER: seabattle
      SEABATTLE_DB_PASS: seabattle
      SEABATTLE_DB_HOST: 127.0.0.1
      SEABATTLE_DB_NAME: seabattle
      SEABATTLE_LANGUAGE: en
      SEABATTLE_GRID_HORIZONTAL_WORD: games
      SEABATTLE_GRID_VERTICAL_WORD: 12345
      SEABATTLE_SHIPS_COUNT: 5
      SEABATTLE_NICKSERV_AUTH_NEEDED: false
      SEABATTLE_NICKSERV_HOST: aitvarasnet.org
      SEABATTLE_NICKSERV_TIMEOUT: 5
      SEABATTLE_LOG_QUERIES: no
    links:
      - ngircd

  ngircd:
    restart: unless-stopped
    image: geekduck/ngircd
    hostname: irc.seabattle.internal
    volumes:
      - $(pwd)/docker-app-configs/ngircd.conf:/etc/ngircd/ngircd.conf:ro

  kiwiirc:
    restart: unless-stopped
    image: boxbox/kiwiirc
    environment:
      KIWI_SERVER_IP: irc.seabattle.internal
      KIWI_SERVER_PORT: 6667
      KIWI_JOIN_CHANNEL: '#seabattle'
      KIWI_NICK: 'kiwi_?'
      KIWI_TITLE: Kiwi IRC
      KIWI_PORT: 80
      KIWI_BIND: 0.0.0.0
    links:
      - ngircd
    volumes:
      - $(pwd)/docker-app-configs/kiwiirc.js:/app/config.js:ro
